version: "3"
services:
  backend:
    container_name: app_backend
    build: backend
    ports:
     - "3200:3200"
    volumes:
     - ./backend:/usr/src/app
     - /usr/src/app/node_modules
    links:
      - db
  frontend:
    container_name: app_frontend
    build: frontend
    ports:
     - "3000:3000"
    volumes:
     - ./frontend:/usr/src/app
     - /usr/src/app/node_modules
    depends_on:
      - backend
  db:
    container_name: db
    image: mongo
    ports:
      - "27017:27017"